# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/CONS.xdc

# IP: c:/Users/22321/Desktop/project/vivado/Exp/Exp1/Exp1-1/IPcore/FullAdder_1/FullAdder.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FullAdder || ORIG_REF_NAME==FullAdder} -quiet] -quiet
