# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/22321/Desktop/project/vivado/Exp/Exp2/FullAdder32/FullAdder32.cache/wt [current_project]
set_property parent.project_path C:/Users/22321/Desktop/project/vivado/Exp/Exp2/FullAdder32/FullAdder32.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/22321/Desktop/project/vivado/Exp/Exp2/IPcore/xilinx.com_user_FullAdder1_1.0 [current_project]
update_ip_catalog
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/22321/Desktop/project/vivado/Exp/Exp2/FullAdder32/FullAdder32.srcs/sources_1/new/FullAdder32.v
  C:/Users/22321/Desktop/project/vivado/Exp/Exp2/FullAdder32/FullAdder32.srcs/sources_1/new/hex_dp.v
  C:/Users/22321/Desktop/project/vivado/Exp/Exp2/FullAdder32/FullAdder32.srcs/sources_1/new/add.v
}
read_ip -quiet c:/Users/22321/Desktop/project/vivado/Exp/Exp1/Exp1-1/IPcore/FullAdder/FullAdder.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/22321/Desktop/project/vivado/Exp/Exp2/FullAdder32/FullAdder32.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/22321/Desktop/project/vivado/Exp/Exp2/FullAdder32/FullAdder32.srcs/constrs_1/new/cons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top add -part xc7a35ticpg236-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef add.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file add_utilization_synth.rpt -pb add_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
